# Generated by Django 5.0.7 on 2024-07-19 15:35

import api.enum
import django_enumfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Truck_ID', models.CharField(max_length=50)),
                ('Asset_Tag', models.CharField(max_length=50)),
                ('Truck_Model', models.CharField(max_length=50)),
                ('ECM_Type', models.CharField(max_length=50)),
                ('status', django_enumfield.db.fields.EnumField(default=0, enum=api.enum.StatusEnum)),
                ('comment', models.TextField()),
            ],
        ),
    ]
