# Generated by Django 5.0.7 on 2024-07-22 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default='some_value', null=True)),
                ('From_Time', models.TimeField(default='')),
                ('To_Time', models.TimeField(default='')),
                ('Truck_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.truck')),
                ('User', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
