# Generated by Django 5.0.7 on 2024-07-24 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_truckbooking'),
        ('schedule', '0014_use_autofields_for_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckCalendar',
            fields=[
                ('calendar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.calendar')),
            ],
            bases=('schedule.calendar',),
        ),
        migrations.CreateModel(
            name='TruckEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.event')),
                ('truck_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.truckbooking')),
            ],
            bases=('schedule.event',),
        ),
    ]
