# Generated by Django 5.0.7 on 2024-08-07 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_truckbooking_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckevent',
            name='event_ptr',
        ),
        migrations.RemoveField(
            model_name='truckevent',
            name='truck_booking',
        ),
        migrations.RemoveField(
            model_name='truckbooking',
            name='slug',
        ),
        migrations.AddField(
            model_name='truckbooking',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='truckbooking',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='truckbooking',
            name='User',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TruckCalendar',
        ),
        migrations.DeleteModel(
            name='TruckEvent',
        ),
    ]
