# Generated by Django 5.0.7 on 2024-08-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_truckevent_event_ptr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truckbooking',
            old_name='Truck_ID',
            new_name='Truck',
        ),
    ]
