# Generated by Django 5.0.7 on 2024-07-16 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
